experiment:
  exp_dir: "/home/mikewu/experiments/bow_12_21"
model:
  input_dim: 284
  hidden_dim: 128
optimizer:
  lr: 1.0e-4
  weight_decay: 0
  batch_size: 16
  max_epochs: 500
  clip_grad_norm: 0.5
machine:
  use_cuda: true
  num_workers: 4
  devices: [0]
  seed: 42
